### ISSUE TITLE
Please Add License

### ISSUE THREAD

**Issue by mikebronner** [ElasticOrange/LaravelMixpanel#1]
Hi. just wanted to comment to please add a license so others can use it as well. :)

**Comment by cleanunicorn** [comment]
@mikebronner I didn't think anyone would like to use it. Just added license file. 
Thanks for the suggestion

**Comment by mikebronner** [comment]
haha, no worries :) thanks! I image there are quire a few "home-brew" projects on github that were intended for internal use only. There weren't many MixPanel packages available for Laravel, and yours was one of them. In the end I did write my own as well, as I wanted to add a bit more functionality to it.

Thanks though for making your package available.
